[script://$SPLUNK_HOME/etc/apps/splunk_citic_alert_action/bin/citic_alert_spool_worker.py]
disabled = 0
interval = 30
python.version = python3
sourcetype = citic:alert:delivery:spool
index = _internal
